CartPole-v1:
  normalize: True
  n_envs: 8
  n_timesteps: !!float 1e5
  policy: 'MlpCfcPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 0.98
  n_epochs: 20
  ent_coef: 0.0
  learning_rate: lin_0.001
  clip_range: lin_0.2
  policy_kwargs: "dict(
                    lstm_kwargs=dict(
                      out_feature=2,
                      hparams=dict(
                        backbone_activation=\"lecun\",
                        backbone_units=64,
                        backbone_dr=0.3,
                        backbone_layers=2,
                        weight_decay=4e-06,
                        optim=\"adamw\",
                        init=0.6,
                        batch_size=128,
                        use_mixed=True,
                        no_gate=False,
                        minimal=False,
                        use_ltc=False,
                      )
                    )
                  )"


Acrobot-v1:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MlpCfcPolicy'
  n_steps: 256
  gae_lambda: 0.94
  gamma: 0.99
  n_epochs: 4
  ent_coef: 0.0
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"


BipedalWalker-v3:
  normalize: true
  n_envs: 32
  n_timesteps: !!float 5e6
  policy: 'MlpCfcPolicy'
  n_steps: 256
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.999
  n_epochs: 10
  ent_coef: 0.0
  learning_rate: !!float 3e-4
  clip_range: 0.18
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"


LunarLander-v2: &lunar-defaults
  normalize: True
  n_envs: 32
  n_timesteps: !!float 5e6
  policy: 'MlpCfcPolicy'
  n_steps: 512
  batch_size: 128
  gae_lambda: 0.98
  gamma: 0.999
  n_epochs: 4
  ent_coef: 0.01
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"